// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLJf_AMx2UYfWMqb88znNgq5ELGqzE8yw',
    appId: '1:53973267839:android:bfd8054159cd45343a564a',
    messagingSenderId: '53973267839',
    projectId: 'flutter-social-login-example',
    storageBucket: 'flutter-social-login-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5gvKBRN75vNV3yeZ3i9LZROVagqED8o',
    appId: '1:53973267839:ios:123732762484c17b3a564a',
    messagingSenderId: '53973267839',
    projectId: 'flutter-social-login-example',
    storageBucket: 'flutter-social-login-example.appspot.com',
    androidClientId: '53973267839-llpd9ka2j6k02tmbpcucfe9gpvkrpr6s.apps.googleusercontent.com',
    iosClientId: '53973267839-ne27dtumf1d452h9a1sbqu1hr7c1g5dl.apps.googleusercontent.com',
    iosBundleId: 'com.betrider.sociallogin',
  );
}
